# RAG System Configuration - Memory Optimized

# Ingestion Settings (Reduced for memory)
ingestion:
  chunk_size: 500 # Reduced from 1000
  chunk_overlap: 100 # Reduced from 200
  max_file_size_mb: 10 # Reduced from 50
  supported_formats: ["pdf", "PDF"]

# OCR Settings (Optimized)
ocr:
  enabled: true
  language: "eng"
  confidence_threshold: 60
  dpi: 200 # Reduced from 300

# Embedding Settings (Memory Optimized)
embeddings:
  model: "all-MiniLM-L6-v2"
  batch_size: 8 # Reduced from 32
  device: "cpu"
  max_seq_length: 256 # Limit sequence length

# Vector Database (Optimized)
vector_db:
  type: "chromadb"
  persist_directory: "./data/vector_db"
  collection_name: "documents"

# Retrieval Settings (Reduced)
retrieval:
  top_k: 3 # Reduced from 5
  similarity_threshold: 0.7
  rerank: false # Disabled for memory

# Generation Settings
generation:
  provider: "ollama"
  model: "llama2"
  max_tokens: 500 # Reduced from 1000
  temperature: 0.7
  ollama_base_url: "http://localhost:11434"
  timeout: 30
  retry_attempts: 2 # Reduced from 3

# Memory Management
memory:
  clear_cache_after_processing: true
  max_concurrent_embeddings: 50
  garbage_collect_frequency: 10
